CoreDemo/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using CoreDemo.Models;
using DataAccessLayer.Concrete;
using DataAccessLayer.Concrete.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
/*
 Authorization İşlemleri
-Yetkilendirme işlemleridir.
-Bir kişinin sisteme giriş yapmadan erişemeyeceği sayfalar ve özelliklerdir.
[Authorize] şeklinde attribute ile authorizing işlmeleri yapılır

Bir yazarın websitesinde olacak nitelikleri
	-Profili
	-Mesaj
	-Blogları
	-Giriş Şifreleri
	-Ayarlar 
	
 */


namespace CoreDemo.Controllers
{	
	/*[Authorize] 2-)buraya yazarsak controllerdeki tüm Actionlara girmek için Authorize gerçekleştirmesi lazım
	ancak her sayfaya teker teker [Authorize] yazmak yerine program.cs dosyasındaki yazdığımız kod bloğu
	 [AllowAnonymous] olan sayfalar hariç her sayfayı [Authorize] yapar. */
	public class WriterController : Controller
	{
		/*1-)Otantike olmadığımız sürece /Writer/Index/ sayfasına giremeyiz 
		[Authorize] tek bir action fonksiyonuna yazarsak sodece o actionun viewi için authorization gereklidir.*/

		WriterManager wm = new WriterManager(new EfWriterRepository());

        [Authorize]
        public IActionResult Index()
		{
			var usermail = User.Identity.Name;
			ViewBag.V = usermail;
			Context c = new Context();
			var writeName = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterName).FirstOrDefault();
			ViewBag.V2 = writeName;
			return View();
		}

		public IActionResult WriterProfile()
		{
			return View();
		}

		public IActionResult WriterMail()
		{
			return View();
		}
		[AllowAnonymous]
		public IActionResult Test()
		{
			return View();
		}

		[AllowAnonymous]
		public PartialViewResult WriterNavbarPartial()
		{
			return PartialView();
		}

		[AllowAnonymous]
		public PartialViewResult WriterFooterPartial()
		{
			return PartialView();
		}



		[AllowAnonymous]
		[HttpGet]
		public IActionResult WriterEditProfile()
		{
            var UserMail = User.Identity.Name;
            Context c = new Context();
			var UserId = c.Writers.Where(x => x.WriterMail == UserMail).Select(y => y.WriterId).FirstOrDefault();


            var writervalues = wm.TGetById(UserId);
			return View(writervalues);
		}


		[AllowAnonymous]
		[HttpPost]
		public IActionResult WriterEditProfile(Writer p)
		{
			WriterValidator wl = new WriterValidator();
			ValidationResult results = wl.Validate(p);
			if (results.IsValid)
			{
				wm.TUpdate(p);
				return RedirectToAction("Index", "DashBoard");
			}
			else
			{
				foreach (var item in results.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
				return View();
			}

		}

        [AllowAnonymous]
        [HttpGet]
		public IActionResult WriterAdd()
		{
			return View();
		}

        [AllowAnonymous]
		[HttpPost]
		public IActionResult WriterAdd(AddProfileImage  p)
		{
			Writer w= new Writer();
			//yazar eklerken bilgisayardan fotoğraf yüklemeye yarar bu fonksiyon parametreden gelen p model klösöründe!
			if(p.WriterImage != null)
			{
				var extension =Path.GetExtension(p.WriterImage.FileName);
				var newimagename = Guid.NewGuid() + extension;
				var location =Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/WriterImageFiles/",newimagename);
				var stream = new FileStream(location,FileMode.Create);
				p.WriterImage.CopyTo(stream);
				w.WriterImage = newimagename;
			}
			p.WriterStatus = true;
			w.WriterMail =p.WriterMail;
			w.WriterName =p.WriterName;	
			w.WriterPassword =p.WriterPassword;
			w.WriterStatus =p.WriterStatus;
			w.WriterAbout =p.WriterAbout;	
			wm.TAdd(w);
			return RedirectToAction("Index", "Dashboard");
		}

	}
}

CoreDemo/Views/Writer/Index.cshtml
@{
    Layout = null;
}
<h1>BURASI YAZAR GİRİŞİ YAPTIKTAN SONRA Kİ PANEL</h1>

<h2>@ViewBag.V</h2>
<br />
<h2>@ViewBag.V2 hoşgeldiniz</h2>

CoreDemo/Views/Writer/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Writer Layout test </h1>

CoreDemo/Views/Writer/WriterAdd.cshtml
@model CoreDemo.Models.AddProfileImage
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
@*enctype klasöre resim kaydetme işlemini yapar*@
<form class="form-group" method="post" enctype="multipart/form-data">
    
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Kayıt Ol</h4>
                <br />
                <div class="form-group">

                    @*idyi hidden ile alınca viewde çıkmıyo ancak veritabanında bu id'ye göre yazıyors*@
                    @Html.HiddenFor(x => x.WriterId, new { @class = "form-control" })
                </div>


                <div class="form-group">
                    <h2> <label for="exampleInputName1">Ad Soyad</label></h2>
                    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                </div>

                <br />     <br />

                <div class="form-group">
                    <h2> <label for="exampleInputEmail3">Mail Adresiniz</label></h2>
                    @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                </div>

                <br />     <br />

                <div class="form-group">
                    <h2><label for="exampleInputPassword4">Yeni Şifre</label></h2>
                    @Html.PasswordFor(x => x.WriterPassword, new { @class = "form-control" })
                </div>

                  <br />     <br />

                <div class="form-group">
                <h2>   <label>Fotoğraf Güncelle</label> </h2>

                        <input type="file"  name="WriterImage"/ >
                </div>

             @*    <div class="form-group">
                    <h2> <label for="exampleInputEmail3">Fotoğraf Ekle</label></h2>
                    @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
                </div> *@

                <br />     <br />

                <div class="form-group">
                    <h2>   <label for="exampleTextarea1">Hakkında</label>  </h2>
                    @Html.TextAreaFor(x => x.WriterAbout, 10, 10, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-outline-success mr-2">Kaydet</button>
                <button class="btn btn-light">İptal Et</button>


            </div>

        </div>

    </div>








</form>

CoreDemo/Views/Writer/WriterEditProfile.cshtml
@model  EntityLayer.Concrete.Writer

@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

 @using (Html.BeginForm("WriterEditProfile","Writer",FormMethod.Post))
        {
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Profil Düzenle</h4>
            <br />
                <div class="form-group">

                    @*idyi hidden ile alınca viewde çıkmıyo ancak veritabanında bu id'ye göre yazıyors*@
                    @Html.HiddenFor(x => x.WriterId, new { @class = "form-control" })
                </div>

       
                <div class="form-group">
					<h2> <label for="exampleInputName1">Ad Soyad</label></h2>
                    @Html.TextBoxFor(x => x.WriterName,new {@class ="form-control"} )
                </div>

                <br />     <br />

                <div class="form-group">
					<h2> <label for="exampleInputEmail3">Mail Adresiniz</label></h2>
					@Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                </div>

                <br />     <br />

                <div class="form-group">
					<h2><label for="exampleInputPassword4">Yeni Şifre</label></h2>
                    @Html.PasswordFor(x => x.WriterPassword, new { @class = "form-control" })
                </div>

              @*   <br />     <br />

                <div class="form-group">
					<h2>   <label>Fotoğraf Güncelle</label> </h2>

                    <input type="file" name="img[]" class="file-upload-default">
                    <div class="input-group col-xs-12">
                        <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
                        <span class="input-group-append">
                            <button class="file-upload-browse btn btn-outline-warning" type="button">Karşıdan Yükle</button>
                        </span>
                    </div>
                </div> *@

                <div class="form-group">
                    <h2> <label for="exampleInputEmail3">Fotoğraf Ekle</label></h2>
                    @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
                </div>

                <br />     <br />

                <div class="form-group">
					<h2>   <label for="exampleTextarea1">Hakkında</label>  </h2>
                    @Html.TextAreaFor(x => x.WriterAbout,10,10, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-outline-success mr-2">Güncelle</button>
                <button class="btn btn-light">İptal Et</button>
          
			 
        </div>

		</div>
			
	</div>
	}		      

CoreDemo/Views/Writer/WriterFooterPartial.cshtml
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Tüm Hakları Saklıdır</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Yazar Paneli <a href="#"> | </a>Core Blog </span>
    </div>
</footer>

CoreDemo/Views/Writer/WriterMail.cshtml
@{
    Layout = null;
}

<h1>Yazar panel alanı</h1>

CoreDemo/Views/Writer/WriterNavbarPartial.cshtml
<nav class="sidebar sidebar-offcanvas"  id="sidebar">
    <ul class="nav" >
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="https://media.licdn.com/dms/image/D4D03AQEEQTSiMrH3Jw/profile-displayphoto-shrink_200_200/0/1715359172294?e=2147483647&v=beta&t=8UkOYVGXTJFX7G-sY3RFe_vKwy0_2XQV4S7fiOuMsBc   " alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">Tayyip Emre Çelik</span>
                    
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/DashBoard/Index/" >
                <span class="menu-title">Ana Sayfa</span>
                <i class="mdi mdi-home menu-icon" style="color: green;"></i>
            </a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterEditProfile/" >
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon" style="color: green;"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogListByWriter/" >
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon" style="color: green;"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogAdd/" >
                <span class="menu-title"> Blog Yaz</span>
                <i class="mdi mdi-lead-pencil menu-icon" style="color: green;"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterMessage/">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-message menu-icon" style="color: green;"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Notification/AllNotification/">
                <span class="menu-title">Bildirimler</span>
                <i class="mdi mdi-bell menu-icon" style="color: green;"></i>
            </a>
        </li>
        

        <li class="nav-item">
            <a class="nav-link" href="/Blog/Index/">
                <span class="menu-title">Siteye Dön</span>
                <i class="mdi mdi-forward menu-icon" style="color: green;"></i>
            </a>
        </li>
		
        <li class="nav-item">
            <a class="nav-link" href="~/Writer/WriterEditProfile/">
				<span class="menu-title">Ayarlar</span>
				<i class="mdi mdi-settings menu-icon" style="color: green;"></i>
			</a>
		</li>

        <li class="nav-item">
            <a class="nav-link" href="~/Login/WriterLogOut/">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-logout menu-icon" style="color: green;"></i>
            </a>
        </li>



    </ul>
</nav>

CoreDemo/Views/Writer/WriterProfile.cshtml
@{
    Layout = null;
}